// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmUMXqjd4jvsLUdf6C1WDVxA54pPsy2io',
    appId: '1:963382140293:web:e41a8f3a6d6d72124c78ec',
    messagingSenderId: '963382140293',
    projectId: 'servtech-6c623',
    authDomain: 'servtech-6c623.firebaseapp.com',
    storageBucket: 'servtech-6c623.firebasestorage.app',
    measurementId: 'G-Z42T2V8SZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2619YI96A2F8ly6sIfDe02K_uo0aXtUs',
    appId: '1:963382140293:android:df11e04aa7a0aec14c78ec',
    messagingSenderId: '963382140293',
    projectId: 'servtech-6c623',
    storageBucket: 'servtech-6c623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcdjpD6wmIG_uvg1Ny8H0IboNE8IGuD9E',
    appId: '1:963382140293:ios:5d5593e90f7f15ff4c78ec',
    messagingSenderId: '963382140293',
    projectId: 'servtech-6c623',
    storageBucket: 'servtech-6c623.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcdjpD6wmIG_uvg1Ny8H0IboNE8IGuD9E',
    appId: '1:963382140293:ios:5d5593e90f7f15ff4c78ec',
    messagingSenderId: '963382140293',
    projectId: 'servtech-6c623',
    storageBucket: 'servtech-6c623.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmUMXqjd4jvsLUdf6C1WDVxA54pPsy2io',
    appId: '1:963382140293:web:f107882f315ed7974c78ec',
    messagingSenderId: '963382140293',
    projectId: 'servtech-6c623',
    authDomain: 'servtech-6c623.firebaseapp.com',
    storageBucket: 'servtech-6c623.firebasestorage.app',
    measurementId: 'G-YQNJBC0E3E',
  );
}
